### ISSUE TITLE
is there any option or api to send message immediately in background??

### ISSUE THREAD

**Issue by ajitgupta123** [KaneCheshire/Communicator#11]
Hi Kane,

Is there any option or API to send message to iPhone from watch immediately when watch is in background?

OR is there any option in watch to make display on always??

I want send message to iPhone from watch in every second.

Please help me to resolve this issue.

Thanks in advance,
Ajit

**Comment by KaneCheshire** [comment]
No, WatchConnectivity doesn't support that since it would be bad for battery life.
