### ISSUE TITLE
Can't seem to make GuaranteedMessage and Blob work

### ISSUE THREAD

**Issue by patrickferreira** [KaneCheshire/Communicator#20]
Hello,

I tried using your sample project to trigger guaranteed and blob transfers.
However, it doesn't seem to work. If I try to use it, I do get the "success" message from the sender device.
However, on the receive device, nothing happens: the data doesn't ever get through.

ImmediateMessage and ImmediateInteractiveMessage works great however.

Any advice how to fix this?

**Comment by patrickferreira** [comment]
Update: Just tried on a real iPhone and watch, works perfectly. Is it supposed to work on the simulator?

**Comment by KaneCheshire** [comment]
It’s a bug on Apple’s side with the simulator since watchOS 6

**Comment by patrickferreira** [comment]
Oh OK!
Thanks for getting back to me this quick 👍
