### ISSUE TITLE
Memory Leak when sending Blob

### ISSUE THREAD

**Issue by FIndustries** [KaneCheshire/Communicator#21]
Hi, I'm using your library which is awesome but I've found a memory leak when sending large blobs.

It seems related to  `NSKeyedArchiver.archivedData` but I'm not sure.

Every time I send a blob the memory never get deallocated leading to crash on the Apple Watch.

<img width="597" src="https://user-images.githubusercontent.com/20090175/83943115-982cf580-a7f9-11ea-92cd-034343aa2e3d.png">

**Comment by KaneCheshire** [comment]
Hey! Thanks for raising this. Is this reproducible in the example app in the repo? If so could you push up a branch I could take a look at? I’ve got a feeling it could be a bug with Apple’s implementation, so if I can reproduce I’ll be able to check.

**Comment by FIndustries** [comment]
I figured out the problem. 
In the watch app I was waiting for a message (`observe`) from the phone and when received I send the large blob. This caused memory leak. 
Calling `Communicator.shared.transfer` in a separate thread fixed the issue.
I still can't figure out why because in the example app it works.
I'll post an update if I find new info.
