### ISSUE TITLE
Communicator.SessionDelegate does not implement delegate method

### ISSUE THREAD

**Issue by Haykaz-Melikyan** [KaneCheshire/Communicator#23]

**Comment by KaneCheshire** [comment]
Can you provide a bit more information?

**Comment by Haykaz-Melikyan** [comment]
> Can you provide a bit more information?

When I try to send GuaranteedMessage to watchKit extension 
let message = GuaranteedMessage.init(identifier: "openWorkouts")
        Communicator.shared.send(message) { (result) in
            print(result) //==  success()
        }

In console "WatchKit Extension[52364:1186650] [WC] -[WCSession onqueue_handleDataMessageRequest:withPairingID:]_block_invoke delegate Communicator.SessionDelegate does not implement delegate method"

WatchKit Extension[52364:1186650] [WC] -[WCSession _onqueue_sendResponseError:identifier:dictionaryMessage:] identifier: 5DA63831-EEEF-4D4B-A1BF-27A0C38265BB with WCErrorCodeDeliveryFailed

and 
GuaranteedMessage.observe { (message) in
//don't handle here
            if message.identifier == "openWorkouts"{
                WKInterfaceController.reloadRootControllers(withNamesAndContexts: [(name: "WorkoutController", context: context as AnyObject)])
            }
        }

thank you for lib and response !

**Comment by KaneCheshire** [comment]
Thanks :) 

Okay a few questions:
- is this on a physical device or simulator?
- what version of iOS and watchOS?
- where are you calling GuaranteedMessage.observe? (It’s best to set this up ASAP in the ExtensionDelegate)

**Comment by Haykaz-Melikyan** [comment]
> Thanks :)
> 
> Okay a few questions:
> 
> * is this on a physical device or simulator?
> * what version of iOS and watchOS?
> * where are you calling GuaranteedMessage.observe? (It’s best to set this up ASAP in the ExtensionDelegate)

1. simulator 
2. iOS 13.5  watchOS 6.2.1
3. I calling in ExtensionDelegate for print() only like your example and in WKInterfaceController in  awake(withContext context: Any?) {}

**Comment by KaneCheshire** [comment]
Can you please try on a device? Since watchOS 6, the simulator has a bug with WatchConnectivity that doesn’t properly send blobs and guaranteed messages, but they work on a device. 

https://github.com/KaneCheshire/Communicator/issues/20

**Comment by Haykaz-Melikyan** [comment]
> Can you please try on a device? Since watchOS 6, the simulator has a bug with WatchConnectivity that doesn’t properly send blobs and guaranteed messages, but they work on a device.
> 
> See here also: #20

yes you are right thanks
one question backgroundOnly Reachability which type of messages work?

**Comment by KaneCheshire** [comment]
No worries. .backgroundOnly means you can send everything except for ImmediateMessage and InteractiveImmediateMessage :)
