### ISSUE TITLE
Blob Transfer observing not working

### ISSUE THREAD

**Issue by JMCPH** [KaneCheshire/Communicator#25]
In the latest version 4.0, the Blob Observe does not work. 

This can be reproduced in the example project.

Anyone else experinced the same problem?

**Comment by KaneCheshire** [comment]
Have you tried on a device? Since watchOS 6 the simulator doesn't transfer background messages with WatchConnectivity 

See also: https://github.com/KaneCheshire/Communicator/issues/20

**Comment by JMCPH** [comment]
Thank you for your quick reply - appreciate it!

I haven't tried on a real device, but will try that later today.

**Comment by JMCPH** [comment]
Thank you for your quick reply - appreciate it!

I'm running this on the 5.3 WatchOS simulator.
I haven't tried on a real device, but will try that later today.

**Comment by KaneCheshire** [comment]
Thanks :) let me know if you have trouble on a device

**Comment by alperengezgin** [comment]
Hi. I tried on Watch 6 real device but blob observe not working. I can send blob watch to iPhone but can't send iPhone to Watch
