### ISSUE TITLE
Build is failing when using Xcode Cloud

### ISSUE THREAD

**Issue by justTreme** [KaneCheshire/Communicator#41]
Hi, im using the latest version of Communicator in my application. Since yesterday all my builds im creating with Xcode Cloud are failing due to the same reason.
I uploaded you the error message Xcode Cloud is giving me.

<img width="1178" alt="Bildschirm­foto 2023-03-22 um 10 05 37" src="https://user-images.githubusercontent.com/10289945/226854030-3932d882-63a9-47d7-8c38-4f7f61cc7af4.png">

**Comment by justTreme** [comment]
My development target is set to watchOS 8.0 and everything else I can select is set automatically to latest version.
Yes, locally it does and I can publish it to TestFlight.

**Comment by KaneCheshire** [comment]
I'm not sure what Xcode Cloud is doing in that case but we probably do something to mitigate it by wrapping that code in an availability check

**Comment by aaronpearce** [comment]
This is occurring in the latest Xcode 14.3 RC1. Waiting on RC2 to download to test there.

**Comment by jmtiimo** [comment]
Yes it's happening in Xcode 14.3. Is there a PR ready for it, or should I look into this?

**Comment by justTreme** [comment]
So far it doesn't look like there is a fix.

**Comment by DavidTiimo** [comment]
Also having issues on Xcode 14.3 (14E222b)

**Comment by FelixLisczyk** [comment]
I've created PR #42 to fix the Xcode 14.3 issues.

**Comment by KaneCheshire** [comment]
Thanks @FelixLisczyk, the PR is merged now and I've pushed an updated tag to the repo

**Comment by fklingenberg** [comment]
I just updated Communicator in my project and can confirm that the problem is fixed.
